#!/bin/sh
base_dir="$(dirname "$0")"
cd "$base_dir"

interpreter="$base_dir/.build/rvk/ethereum-kompiled/interpreter"
kast="$(mktemp)"
output="$(mktemp)"
kast_output="$(mktemp)"
trap "rm -rf $kast $output $kast_output" INT TERM EXIT
./kast-json.py "$1" > "$kast"
$interpreter "$base_dir/k/ethereum-kompiled/realdef.cma" -c PGM "$kast" textfile -c SCHEDULE '`DEFAULT_ETHEREUM`(.KList)' text -c MODE '`VMTESTS_ETHEREUM`(.KList)' text --output-file "$output"
exit=$?
if [ $exit -eq 0 ]; then
  exit 0
fi
k-bin-to-text "$output" "$kast_output"
cat "$kast_output"
printf "\n"
exit $exit
